name: Check Apollo Graph

on:
  workflow_call:
    secrets:
      NODE_AUTH_TOKEN:
        required: true
      APOLLO_KEY:
        required: true

jobs:
  test:
    name: Check Gateway Server
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        registry-url: https://npm.pkg.github.com/
        scope: '@dashboardlabs'
    - run: npm ci
    - run: npm run build
    - run: echo "REPO_NAME=$(echo "${{ github.repository }}" | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
    - run: npx -p @dashboardlabs/dashdev dashdev graphql:schema ./dist/src.js | npx -p @apollo/rover rover subgraph check dashlabsai@develop --name ${{ env.REPO_NAME }} --schema -
