name: Docker Build

on:
  workflow_call:
    inputs:
      nextjs-project:
        required: false
        default: false
        type: boolean
    secrets:
      HARBOR_AUTH_USERNAME:
        required: false
      HARBOR_AUTH_SECRET:
        required: false
      NODE_AUTH_TOKEN:
        required: true
      GOOGLE_AUTH_TOKEN:
        required: false

jobs:
  build_google:
    name: Build Docker Image (GCP Artifact Registry)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Download NextJS Build Output
      uses: actions/download-artifact@v2
      if: inputs.nextjs-project
      with:
        name: nextjs-output

    - name: Download NextJS Build Output
      uses: actions/download-artifact@v2
      if: inputs.nextjs-project
      with:
        name: routes-manifest

    - name: 'Untar files'
      if: inputs.nextjs-project
      run: tar -xvf nextjs-output.tar ./out/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Google Cloud Auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_AUTH_TOKEN }}'

    - name: 'Set up Google Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Get GCP Docker Credentials
      run: |-
        gcloud auth configure-docker --quiet asia-southeast1-docker.pkg.dev

    - name: Set Docker Repo
      run: echo "VERSION=$(echo "${{ github.ref }}" | grep "develop" > /dev/null && echo "dev" || echo "prod")" >> $GITHUB_ENV

    - name: Get Repository Name
      run: echo "REPO_NAME=$(echo "${{ github.repository }}" | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV

    - name: Build and Push
      uses: docker/build-push-action@v2
      id: build-docker-image
      with:
        context: .
        push: true
        tags: asia-southeast1-docker.pkg.dev/dashlabs/${{ env.VERSION }}/${{ env.REPO_NAME }}:latest
        build-args: |
          NPM_TOKEN="${{ secrets.NODE_AUTH_TOKEN }}"

    - name: Save Docker Digest
      run: echo "${{ steps.build-docker-image.outputs.digest }}" > digest-gar.txt

    - name: Upload Docker Digest
      uses: actions/upload-artifact@v2
      with:
        name: digest-gar
        path: digest-gar.txt
  # build:
  #   name: Build Docker Image
  #   runs-on: [self-hosted, gcp-dashlabs-private-network]
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Download NextJS Build Output
  #     uses: actions/download-artifact@v2
  #     if: inputs.nextjs-project
  #     with:
  #       name: nextjs-output

  #   - name: 'Untar files'
  #     if: inputs.nextjs-project
  #     run: tar -xvf nextjs-output.tar ./out/

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v1

  #   - name: Login to DockerHub
  #     uses: docker/login-action@v1 
  #     with:
  #       registry: registry.dashlabs.xyz
  #       username: ${{ secrets.HARBOR_AUTH_USERNAME }}
  #       password: ${{ secrets.HARBOR_AUTH_SECRET }}

  #   - name: Set Docker Image Version
  #     run: echo "VERSION=$(echo "${{ github.ref }}" | grep "develop" > /dev/null && echo "develop" || (echo "${{ github.ref }}" | grep "delta" > /dev/null && echo "delta" || echo "latest"))" >> $GITHUB_ENV

  #   - name: Get Repository Name
  #     run: echo "REPO_NAME=$(echo "${{ github.repository }}" | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV

  #   - name: Build and Push
  #     uses: docker/build-push-action@v2
  #     id: build-docker-image
  #     with:
  #       context: .
  #       push: true
  #       tags: registry.dashlabs.xyz/dashlabsai/${{ env.REPO_NAME }}:${{ env.VERSION }}
  #       build-args: |
  #         NPM_TOKEN="${{ secrets.NODE_AUTH_TOKEN }}"
  #       # cache-from: type=gha
  #       # cache-to: type=gha,mode=max

  #   - name: Save Docker Digest
  #     run: echo "${{ steps.build-docker-image.outputs.digest }}" > digest.txt

  #   - name: Upload Docker Digest
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: digest
  #       path: digest.txt
