name: Sync Branches

on:
  workflow_call:
    inputs:
      use-gh-app:
        required: false
        default: false
        type: boolean
    secrets:
      NODE_AUTH_TOKEN:
        required: false
      GH_APP_ID:
        required: false
      GH_APP_PRIVATE_KEY:
        required: false

jobs:
  master_to_develop:
    name: Sync Master to Develop
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Merge master -> develop
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        from_branch: master
        target_branch: develop
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get Token
      id: token
      uses: getsentry/action-github-app-token@v1
      if: inputs.use-gh-app
      with:
        app_id: ${{ secrets.GH_APP_ID }}
        private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
    - name: Trigger Docker Deploy (develop)
      uses: benc-uk/workflow-dispatch@v1
      if: inputs.use-gh-app
      with:
        workflow: Docker Build
        token: ${{ steps.token.outputs.token }}
        ref: refs/heads/develop
    - name: Trigger Docker Deploy (develop)
      uses: benc-uk/workflow-dispatch@v1
      if: inputs.use-gh-app == false
      with:
        workflow: Docker Build
        token: ${{ secrets.NODE_AUTH_TOKEN }}
        ref: refs/heads/develop
